### ISSUE TITLE
prepare_vectorx_boosting_dataset: wrote 0 articles

### ISSUE THREAD

**Issue by seliverstov** [deepmipt/rus_ner_dataset#2]
Запускаю код который генерит toloka_2017-08-01_boost.tsv и в результате получаю пустой файл.

**Comment by tsundokum** [comment]
Этот файл не был готов, там не привязана модель, которая делает изначальный тэггинг предложений. его нужно внимательно прочитать и дописать

**Comment by seliverstov** [comment]
Собственно там файл пустой из-за условия
if int(guid) % 5 == 0:
            break
которое стопает цикл. Какой смысл закладывался в эту проверку?

**Comment by tsundokum** [comment]
это чтобы уменьшить выборку, взять примерно 1/5 из новостей

**Comment by seliverstov** [comment]
ок
